# Generated by Django 3.2.6 on 2021-08-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaddyAreaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddy_area_name', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=20)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaddyAreaDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_confidence', models.FloatField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.disease')),
            ],
        ),
        migrations.CreateModel(
            name='PaddyAreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('paddy_height', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('water_level', models.FloatField()),
                ('soil_nitrogen', models.FloatField(default=0)),
                ('paddy_images', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('disease', models.ManyToManyField(through='dashboard.PaddyAreaDisease', to='information.Disease')),
                ('paddy_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.paddyareadetail')),
            ],
        ),
        migrations.CreateModel(
            name='PaddyAreaRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_confidence', models.FloatField()),
                ('paddy_area_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paddyareainfo')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.risk')),
            ],
        ),
        migrations.AddField(
            model_name='paddyareainfo',
            name='risk',
            field=models.ManyToManyField(through='dashboard.PaddyAreaRisk', to='information.Risk'),
        ),
        migrations.AddField(
            model_name='paddyareadisease',
            name='paddy_area_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paddyareainfo'),
        ),
    ]
