# Generated by Django 3.2.6 on 2021-08-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20210827_1726'),
        ('dashboard', '0002_auto_20210827_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddyareariskdisease',
            name='risk_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.risk_disease'),
        ),
        migrations.AddField(
            model_name='paddyareainfo',
            name='risk_disease',
            field=models.ManyToManyField(through='dashboard.PaddyAreaRiskDisease', to='information.Risk_Disease'),
        ),
    ]
