# Generated by Django 3.2.6 on 2021-08-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_paddy_area_name_paddyareadetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddyareariskdisease',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
