# Generated by Django 3.2.6 on 2021-09-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_testimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddyareainfo',
            name='paddy_images',
            field=models.ImageField(blank=True, default='default.png', upload_to='info_images'),
        ),
        migrations.AlterField(
            model_name='testimage',
            name='paddy_images',
            field=models.ImageField(blank=True, default='default.png', upload_to='test_images'),
        ),
    ]
