# Generated by Django 3.2.6 on 2021-09-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210902_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddyareainfo',
            name='soil_pH',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='paddyareainfo',
            name='soil_phosphorous',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='paddyareainfo',
            name='soil_potassium',
            field=models.FloatField(default=0),
        ),
    ]
