# Generated by Django 3.2.6 on 2021-09-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210903_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='paddyareainfo',
            name='rail_fall',
            field=models.FloatField(default=0),
        ),
    ]
