# Generated by Django 3.2.6 on 2021-09-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_rail_fall_paddyareainfo_rain_fall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paddyareainfo',
            old_name='soil_phosphorous',
            new_name='soil_phosphorus',
        ),
    ]
