# Generated by Django 3.2.6 on 2021-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_soil_phosphorous_paddyareainfo_soil_phosphorus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('water_level', models.FloatField()),
                ('soil_nitrogen', models.FloatField(default=0)),
                ('soil_phosphorus', models.FloatField(default=0)),
                ('soil_potassium', models.FloatField(default=0)),
                ('soil_pH', models.FloatField(default=0)),
            ],
        ),
    ]
