# Generated by Django 3.2.6 on 2021-09-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_testinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='rain_fall',
            field=models.FloatField(default=0),
        ),
    ]
