# Generated by Django 3.2.6 on 2021-08-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210827_1726'),
        ('information', '0002_auto_20210827_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Risk_Disease',
            new_name='RiskDisease',
        ),
    ]
