# Generated by Django 3.2.6 on 2021-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_rename_risk_disease_riskdisease'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdisease',
            name='risk_disease_images',
            field=models.ImageField(blank=True, default='default.png', upload_to='risk_disease_images'),
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_images',
            field=models.ImageField(blank=True, default='default.png', upload_to='solution_images'),
        ),
    ]
