# Generated by Django 3.2.6 on 2021-09-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20210902_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskdisease',
            old_name='risk_disease_images',
            new_name='risk_disease_image',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='solution_images',
            new_name='solution_image',
        ),
    ]
