# Generated by Django 3.2.6 on 2021-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20210903_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='riskdisease',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
